export const SKILL_OPTIONS = [
  { value: 'JavaScript', label: 'JavaScript' }, { value: 'Python', label: 'Python' }, { value: 'Java', label: 'Java' }, { value: 'C++', label: 'C++' }, { value: 'C#', label: 'C#' }, { value: 'TypeScript', label: 'TypeScript' }, { value: 'Go', label: 'Go' }, { value: 'Rust', label: 'Rust' }, { value: 'Swift', label: 'Swift' }, { value: 'Kotlin', label: 'Kotlin' }, { value: 'PHP', label: 'PHP' }, { value: 'Ruby', label: 'Ruby' }, { value: 'HTML/CSS', label: 'HTML/CSS' },
  { value: 'React.js', label: 'React.js' }, { value: 'Angular', label: 'Angular' }, { value: 'Vue.js', label: 'Vue.js' }, { value: 'Next.js', label: 'Next.js' }, { value: 'Tailwind CSS', label: 'Tailwind CSS' }, { value: 'Redux', label: 'Redux' }, { value: 'Bootstrap', label: 'Bootstrap' },
  { value: 'Node.js', label: 'Node.js' }, { value: 'Express.js', label: 'Express.js' }, { value: 'Django', label: 'Django' }, { value: 'Flask', label: 'Flask' }, { value: 'Spring Boot', label: 'Spring Boot' }, { value: 'SQL', label: 'SQL' }, { value: 'MySQL', label: 'MySQL' }, { value: 'PostgreSQL', label: 'PostgreSQL' }, { value: 'MongoDB', label: 'MongoDB' }, { value: 'Redis', label: 'Redis' }, { value: 'Firebase', label: 'Firebase' },
  { value: 'AWS', label: 'AWS' }, { value: 'Microsoft Azure', label: 'Microsoft Azure' }, { value: 'Google Cloud (GCP)', label: 'Google Cloud (GCP)' }, { value: 'Docker', label: 'Docker' }, { value: 'Kubernetes', label: 'Kubernetes' }, { value: 'Jenkins', label: 'Jenkins' }, { value: 'Git/GitHub', label: 'Git/GitHub' }, { value: 'Linux', label: 'Linux' }, { value: 'CI/CD', label: 'CI/CD' },
  { value: 'Machine Learning', label: 'Machine Learning' }, { value: 'Artificial Intelligence', label: 'Artificial Intelligence' }, { value: 'Data Science', label: 'Data Science' }, { value: 'Pandas', label: 'Pandas' }, { value: 'NumPy', label: 'NumPy' }, { value: 'TensorFlow', label: 'TensorFlow' }, { value: 'PyTorch', label: 'PyTorch' }, { value: 'NLP', label: 'NLP' }, { value: 'Computer Vision', label: 'Computer Vision' }, { value: 'Data Analysis', label: 'Data Analysis' }, { value: 'Power BI', label: 'Power BI' }, { value: 'Tableau', label: 'Tableau' },
  { value: 'React Native', label: 'React Native' }, { value: 'Flutter', label: 'Flutter' }, { value: 'Android Development', label: 'Android Development' }, { value: 'iOS Development', label: 'iOS Development' }, { value: 'UI/UX Design', label: 'UI/UX Design' }, { value: 'Figma', label: 'Figma' }, { value: 'Adobe XD', label: 'Adobe XD' }, { value: 'Cyber Security', label: 'Cyber Security' }, { value: 'Blockchain', label: 'Blockchain' }, { value: 'Web3', label: 'Web3' }, { value: 'Internet of Things (IoT)', label: 'Internet of Things (IoT)' }, { value: 'Robotics', label: 'Robotics' }, { value: 'Agile/Scrum', label: 'Agile/Scrum' }, { value: 'Project Management', label: 'Project Management' }
];

export const LOCATION_OPTIONS = [
  { value: 'Remote', label: 'Remote' },
  { value: 'Mumbai, Maharashtra', label: 'Mumbai, Maharashtra' }, { value: 'Delhi, NCR', label: 'Delhi, NCR' }, { value: 'Bangalore, Karnataka', label: 'Bangalore, Karnataka' }, { value: 'Hyderabad, Telangana', label: 'Hyderabad, Telangana' }, { value: 'Chennai, Tamil Nadu', label: 'Chennai, Tamil Nadu' }, { value: 'Kolkata, West Bengal', label: 'Kolkata, West Bengal' }, { value: 'Pune, Maharashtra', label: 'Pune, Maharashtra' }, { value: 'Ahmedabad, Gujarat', label: 'Ahmedabad, Gujarat' },
  { value: 'Gurgaon, Haryana', label: 'Gurgaon, Haryana' }, { value: 'Noida, Uttar Pradesh', label: 'Noida, Uttar Pradesh' }, { value: 'Jaipur, Rajasthan', label: 'Jaipur, Rajasthan' }, { value: 'Surat, Gujarat', label: 'Surat, Gujarat' }, { value: 'Lucknow, Uttar Pradesh', label: 'Lucknow, Uttar Pradesh' }, { value: 'Kanpur, Uttar Pradesh', label: 'Kanpur, Uttar Pradesh' }, { value: 'Nagpur, Maharashtra', label: 'Nagpur, Maharashtra' }, { value: 'Indore, Madhya Pradesh', label: 'Indore, Madhya Pradesh' }, { value: 'Thane, Maharashtra', label: 'Thane, Maharashtra' }, { value: 'Bhopal, Madhya Pradesh', label: 'Bhopal, Madhya Pradesh' }, { value: 'Visakhapatnam, Andhra Pradesh', label: 'Visakhapatnam, Andhra Pradesh' }, { value: 'Patna, Bihar', label: 'Patna, Bihar' }, { value: 'Vadodara, Gujarat', label: 'Vadodara, Gujarat' }, { value: 'Ghaziabad, Uttar Pradesh', label: 'Ghaziabad, Uttar Pradesh' }, { value: 'Ludhiana, Punjab', label: 'Ludhiana, Punjab' }, { value: 'Agra, Uttar Pradesh', label: 'Agra, Uttar Pradesh' }, { value: 'Nashik, Maharashtra', label: 'Nashik, Maharashtra' }, { value: 'Faridabad, Haryana', label: 'Faridabad, Haryana' }, { value: 'Meerut, Uttar Pradesh', label: 'Meerut, Uttar Pradesh' }, { value: 'Rajkot, Gujarat', label: 'Rajkot, Gujarat' }, { value: 'Varanasi, Uttar Pradesh', label: 'Varanasi, Uttar Pradesh' }, { value: 'Srinagar, J&K', label: 'Srinagar, J&K' }, { value: 'Aurangabad, Maharashtra', label: 'Aurangabad, Maharashtra' }, { value: 'Dhanbad, Jharkhand', label: 'Dhanbad, Jharkhand' }, { value: 'Amritsar, Punjab', label: 'Amritsar, Punjab' }, { value: 'Allahabad, Uttar Pradesh', label: 'Allahabad, Uttar Pradesh' }, { value: 'Ranchi, Jharkhand', label: 'Ranchi, Jharkhand' }, { value: 'Gwalior, Madhya Pradesh', label: 'Gwalior, Madhya Pradesh' }, { value: 'Coimbatore, Tamil Nadu', label: 'Coimbatore, Tamil Nadu' }, { value: 'Vijayawada, Andhra Pradesh', label: 'Vijayawada, Andhra Pradesh' }, { value: 'Jodhpur, Rajasthan', label: 'Jodhpur, Rajasthan' }, { value: 'Madurai, Tamil Nadu', label: 'Madurai, Tamil Nadu' }, { value: 'Raipur, Chhattisgarh', label: 'Raipur, Chhattisgarh' }, { value: 'Kota, Rajasthan', label: 'Kota, Rajasthan' }, { value: 'Guwahati, Assam', label: 'Guwahati, Assam' }, { value: 'Chandigarh', label: 'Chandigarh' }, { value: 'Mysore, Karnataka', label: 'Mysore, Karnataka' }, { value: 'Bhubaneswar, Odisha', label: 'Bhubaneswar, Odisha' }, { value: 'Thiruvananthapuram, Kerala', label: 'Thiruvananthapuram, Kerala' }, { value: 'Kochi, Kerala', label: 'Kochi, Kerala' }, { value: 'Dehradun, Uttarakhand', label: 'Dehradun, Uttarakhand' }, { value: 'Jamshedpur, Jharkhand', label: 'Jamshedpur, Jharkhand' }
];

export const EDUCATION_OPTIONS = [
  { value: 'IIT Bombay', label: 'IIT Bombay' }, { value: 'IIT Delhi', label: 'IIT Delhi' }, { value: 'IIT Kanpur', label: 'IIT Kanpur' }, { value: 'IIT Madras', label: 'IIT Madras' }, { value: 'IIT Kharagpur', label: 'IIT Kharagpur' }, { value: 'IIT Roorkee', label: 'IIT Roorkee' }, { value: 'IIT Guwahati', label: 'IIT Guwahati' }, { value: 'IIT Hyderabad', label: 'IIT Hyderabad' },
  { value: 'NIT Trichy', label: 'NIT Trichy' }, { value: 'NIT Surathkal', label: 'NIT Surathkal' }, { value: 'NIT Warangal', label: 'NIT Warangal' }, { value: 'NIT Calicut', label: 'NIT Calicut' }, { value: 'NIT Rourkela', label: 'NIT Rourkela' }, { value: 'IIIT Hyderabad', label: 'IIIT Hyderabad' }, { value: 'IIIT Bangalore', label: 'IIIT Bangalore' }, { value: 'IIIT Allahabad', label: 'IIIT Allahabad' },
  { value: 'BITS Pilani', label: 'BITS Pilani' }, { value: 'VIT Vellore', label: 'VIT Vellore' }, { value: 'SRM Institute of Science and Technology', label: 'SRM Institute of Science and Technology' }, { value: 'Manipal Institute of Technology (MIT)', label: 'Manipal Institute of Technology (MIT)' }, { value: 'Thapar Institute of Engineering and Technology', label: 'Thapar Institute of Engineering and Technology' }, { value: 'Amity University', label: 'Amity University' }, { value: 'KIIT, Bhubaneswar', label: 'KIIT, Bhubaneswar' }, { value: 'Delhi University (DU)', label: 'Delhi University (DU)' }, { value: 'Mumbai University', label: 'Mumbai University' }, { value: 'Pune University (SPPU)', label: 'Pune University (SPPU)' }, { value: 'S.B. Patil College of Engineering, Pune', label: 'S.B. Patil College of Engineering, Pune' }, { value: 'Calcutta University', label: 'Calcutta University' }, { value: 'Jadavpur University', label: 'Jadavpur University' }, { value: 'Anna University', label: 'Anna University' }, { value: 'Osmania University', label: 'Osmania University' }, { value: 'IISc Bangalore', label: 'IISc Bangalore' }, { value: 'IISER Pune', label: 'IISER Pune' },
  { value: 'Self-Taught', label: 'Self-Taught' }, { value: 'Bootcamp Graduate', label: 'Bootcamp Graduate' }
];