"""Removed Group and GroupInvite models

Revision ID: 14ee0c832769
Revises: 4c5201e8dbdb
Create Date: 2026-02-15 19:05:03.338006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ee0c832769'
down_revision = '4c5201e8dbdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_members')
    op.drop_table('group_invite')
    op.drop_table('group')
   
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_invite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('group_invite_group_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('group_invite_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('group_invite_pkey'))
    )
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('group_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name='group_creator_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='group_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('group_members',
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('group_members_group_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('group_members_user_id_fkey')),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('group_members_pkey'))
    )
    # ### end Alembic commands ###
