"""Add user_recommendation table

Revision ID: 49f2a98eafc2
Revises: 23e4645406d5
Create Date: 2026-04-05 22:55:10.841814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f2a98eafc2'
down_revision = '23e4645406d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('recommended_user_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recommended_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recommended_user_id', name='uq_user_recommendation')
    )
    with op.batch_alter_table('user_recommendation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_recommendation_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_like_user_post'))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('idx_post_likes_count'))
        batch_op.drop_index(batch_op.f('idx_post_timestamp'))
        batch_op.drop_index(batch_op.f('idx_post_user_id'))
        batch_op.drop_index(batch_op.f('post_desc_trgm_idx'), postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.drop_index(batch_op.f('post_title_trgm_idx'), postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')

    with op.batch_alter_table('saved_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_saved_user_post'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_user_skills_trgm'), postgresql_ops={'skills': 'gin_trgm_ops'}, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_skills_trgm'), ['skills'], unique=False, postgresql_ops={'skills': 'gin_trgm_ops'}, postgresql_using='gin')

    with op.batch_alter_table('saved_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_saved_user_post'), ['user_id', 'post_id'], unique=False)

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('post_title_trgm_idx'), ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index(batch_op.f('post_desc_trgm_idx'), ['description'], unique=False, postgresql_ops={'description': 'gin_trgm_ops'}, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_post_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_post_timestamp'), [sa.literal_column('timestamp DESC')], unique=False)
        batch_op.create_index(batch_op.f('idx_post_likes_count'), [sa.literal_column('likes_count DESC')], unique=False)
        batch_op.alter_column('likes_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_like_user_post'), ['user_id', 'post_id'], unique=False)

    with op.batch_alter_table('user_recommendation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_recommendation_user_id'))

    op.drop_table('user_recommendation')
    # ### end Alembic commands ###
