"""Added profile_pic and github_repo to Team

Revision ID: d9df22e92d29
Revises: 5e627c30b2c6
Create Date: 2026-02-18 02:37:03.454765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9df22e92d29'
down_revision = '5e627c30b2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('github_repo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('github_repo')
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
