"""empty message

Revision ID: f1b02052688d
Revises: 49f2a98eafc2
Create Date: 2026-04-10 23:26:04.537102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b02052688d'
down_revision = '49f2a98eafc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('proof_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('proof_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('proof_image')
        batch_op.drop_column('proof_link')
        batch_op.drop_column('proof_text')

    # ### end Alembic commands ###
